name: "airflow_dbt_local_1000_models"
version: "1.0.0"
config-version: 2

profile: "airflow_dbt_local_1000_models"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airflow_dbt_local_1000_models:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
